export type SurahSeed = {
  number: number;
  nameAr: string;
  nameEn: string;
  ayahCount: number;
  juz: number;
};

/** Canonical 114 surahs — global reference data (not per-tenant). */
export const SURAHS: SurahSeed[] = [
  { number: 1, nameAr: "الفاتحة", nameEn: "Al-Fatihah", ayahCount: 7, juz: 1 },
  { number: 2, nameAr: "البقرة", nameEn: "Al-Baqarah", ayahCount: 286, juz: 1 },
  { number: 3, nameAr: "آل عمران", nameEn: "Ali Imran", ayahCount: 200, juz: 3 },
  { number: 4, nameAr: "النساء", nameEn: "An-Nisa", ayahCount: 176, juz: 4 },
  { number: 5, nameAr: "المائدة", nameEn: "Al-Maidah", ayahCount: 120, juz: 6 },
  { number: 6, nameAr: "الأنعام", nameEn: "Al-Anam", ayahCount: 165, juz: 7 },
  { number: 7, nameAr: "الأعراف", nameEn: "Al-Araf", ayahCount: 206, juz: 8 },
  { number: 8, nameAr: "الأنفال", nameEn: "Al-Anfal", ayahCount: 75, juz: 9 },
  { number: 9, nameAr: "التوبة", nameEn: "At-Tawbah", ayahCount: 129, juz: 10 },
  { number: 10, nameAr: "يونس", nameEn: "Yunus", ayahCount: 109, juz: 11 },
  { number: 11, nameAr: "هود", nameEn: "Hud", ayahCount: 123, juz: 11 },
  { number: 12, nameAr: "يوسف", nameEn: "Yusuf", ayahCount: 111, juz: 12 },
  { number: 13, nameAr: "الرعد", nameEn: "Ar-Rad", ayahCount: 43, juz: 13 },
  { number: 14, nameAr: "إبراهيم", nameEn: "Ibrahim", ayahCount: 52, juz: 13 },
  { number: 15, nameAr: "الحجر", nameEn: "Al-Hijr", ayahCount: 99, juz: 14 },
  { number: 16, nameAr: "النحل", nameEn: "An-Nahl", ayahCount: 128, juz: 14 },
  { number: 17, nameAr: "الإسراء", nameEn: "Al-Isra", ayahCount: 111, juz: 15 },
  { number: 18, nameAr: "الكهف", nameEn: "Al-Kahf", ayahCount: 110, juz: 15 },
  { number: 19, nameAr: "مريم", nameEn: "Maryam", ayahCount: 98, juz: 16 },
  { number: 20, nameAr: "طه", nameEn: "Taha", ayahCount: 135, juz: 16 },
  { number: 21, nameAr: "الأنبياء", nameEn: "Al-Anbiya", ayahCount: 112, juz: 17 },
  { number: 22, nameAr: "الحج", nameEn: "Al-Hajj", ayahCount: 78, juz: 17 },
  { number: 23, nameAr: "المؤمنون", nameEn: "Al-Muminun", ayahCount: 118, juz: 18 },
  { number: 24, nameAr: "النور", nameEn: "An-Nur", ayahCount: 64, juz: 18 },
  { number: 25, nameAr: "الفرقان", nameEn: "Al-Furqan", ayahCount: 77, juz: 18 },
  { number: 26, nameAr: "الشعراء", nameEn: "Ash-Shuara", ayahCount: 227, juz: 19 },
  { number: 27, nameAr: "النمل", nameEn: "An-Naml", ayahCount: 93, juz: 19 },
  { number: 28, nameAr: "القصص", nameEn: "Al-Qasas", ayahCount: 88, juz: 20 },
  { number: 29, nameAr: "العنكبوت", nameEn: "Al-Ankabut", ayahCount: 69, juz: 20 },
  { number: 30, nameAr: "الروم", nameEn: "Ar-Rum", ayahCount: 60, juz: 21 },
  { number: 31, nameAr: "لقمان", nameEn: "Luqman", ayahCount: 34, juz: 21 },
  { number: 32, nameAr: "السجدة", nameEn: "As-Sajdah", ayahCount: 30, juz: 21 },
  { number: 33, nameAr: "الأحزاب", nameEn: "Al-Ahzab", ayahCount: 73, juz: 21 },
  { number: 34, nameAr: "سبأ", nameEn: "Saba", ayahCount: 54, juz: 22 },
  { number: 35, nameAr: "فاطر", nameEn: "Fatir", ayahCount: 45, juz: 22 },
  { number: 36, nameAr: "يس", nameEn: "Ya-Sin", ayahCount: 83, juz: 22 },
  { number: 37, nameAr: "الصافات", nameEn: "As-Saffat", ayahCount: 182, juz: 23 },
  { number: 38, nameAr: "ص", nameEn: "Sad", ayahCount: 88, juz: 23 },
  { number: 39, nameAr: "الزمر", nameEn: "Az-Zumar", ayahCount: 75, juz: 23 },
  { number: 40, nameAr: "غافر", nameEn: "Ghafir", ayahCount: 85, juz: 24 },
  { number: 41, nameAr: "فصلت", nameEn: "Fussilat", ayahCount: 54, juz: 24 },
  { number: 42, nameAr: "الشورى", nameEn: "Ash-Shura", ayahCount: 53, juz: 25 },
  { number: 43, nameAr: "الزخرف", nameEn: "Az-Zukhruf", ayahCount: 89, juz: 25 },
  { number: 44, nameAr: "الدخان", nameEn: "Ad-Dukhan", ayahCount: 59, juz: 25 },
  { number: 45, nameAr: "الجاثية", nameEn: "Al-Jathiyah", ayahCount: 37, juz: 25 },
  { number: 46, nameAr: "الأحقاف", nameEn: "Al-Ahqaf", ayahCount: 35, juz: 26 },
  { number: 47, nameAr: "محمد", nameEn: "Muhammad", ayahCount: 38, juz: 26 },
  { number: 48, nameAr: "الفتح", nameEn: "Al-Fath", ayahCount: 29, juz: 26 },
  { number: 49, nameAr: "الحجرات", nameEn: "Al-Hujurat", ayahCount: 18, juz: 26 },
  { number: 50, nameAr: "ق", nameEn: "Qaf", ayahCount: 45, juz: 26 },
  { number: 51, nameAr: "الذاريات", nameEn: "Adh-Dhariyat", ayahCount: 60, juz: 26 },
  { number: 52, nameAr: "الطور", nameEn: "At-Tur", ayahCount: 49, juz: 27 },
  { number: 53, nameAr: "النجم", nameEn: "An-Najm", ayahCount: 62, juz: 27 },
  { number: 54, nameAr: "القمر", nameEn: "Al-Qamar", ayahCount: 55, juz: 27 },
  { number: 55, nameAr: "الرحمن", nameEn: "Ar-Rahman", ayahCount: 78, juz: 27 },
  { number: 56, nameAr: "الواقعة", nameEn: "Al-Waqiah", ayahCount: 96, juz: 27 },
  { number: 57, nameAr: "الحديد", nameEn: "Al-Hadid", ayahCount: 29, juz: 27 },
  { number: 58, nameAr: "المجادلة", nameEn: "Al-Mujadila", ayahCount: 22, juz: 28 },
  { number: 59, nameAr: "الحشر", nameEn: "Al-Hashr", ayahCount: 24, juz: 28 },
  { number: 60, nameAr: "الممتحنة", nameEn: "Al-Mumtahanah", ayahCount: 13, juz: 28 },
  { number: 61, nameAr: "الصف", nameEn: "As-Saff", ayahCount: 14, juz: 28 },
  { number: 62, nameAr: "الجمعة", nameEn: "Al-Jumuah", ayahCount: 11, juz: 28 },
  { number: 63, nameAr: "المنافقون", nameEn: "Al-Munafiqun", ayahCount: 11, juz: 28 },
  { number: 64, nameAr: "التغابن", nameEn: "At-Taghabun", ayahCount: 18, juz: 28 },
  { number: 65, nameAr: "الطلاق", nameEn: "At-Talaq", ayahCount: 12, juz: 28 },
  { number: 66, nameAr: "التحريم", nameEn: "At-Tahrim", ayahCount: 12, juz: 28 },
  { number: 67, nameAr: "الملك", nameEn: "Al-Mulk", ayahCount: 30, juz: 29 },
  { number: 68, nameAr: "القلم", nameEn: "Al-Qalam", ayahCount: 52, juz: 29 },
  { number: 69, nameAr: "الحاقة", nameEn: "Al-Haqqah", ayahCount: 52, juz: 29 },
  { number: 70, nameAr: "المعارج", nameEn: "Al-Maarij", ayahCount: 44, juz: 29 },
  { number: 71, nameAr: "نوح", nameEn: "Nuh", ayahCount: 28, juz: 29 },
  { number: 72, nameAr: "الجن", nameEn: "Al-Jinn", ayahCount: 28, juz: 29 },
  { number: 73, nameAr: "المزمل", nameEn: "Al-Muzzammil", ayahCount: 20, juz: 29 },
  { number: 74, nameAr: "المدثر", nameEn: "Al-Muddaththir", ayahCount: 56, juz: 29 },
  { number: 75, nameAr: "القيامة", nameEn: "Al-Qiyamah", ayahCount: 40, juz: 29 },
  { number: 76, nameAr: "الإنسان", nameEn: "Al-Insan", ayahCount: 31, juz: 29 },
  { number: 77, nameAr: "المرسلات", nameEn: "Al-Mursalat", ayahCount: 50, juz: 29 },
  { number: 78, nameAr: "النبأ", nameEn: "An-Naba", ayahCount: 40, juz: 30 },
  { number: 79, nameAr: "النازعات", nameEn: "An-Naziat", ayahCount: 46, juz: 30 },
  { number: 80, nameAr: "عبس", nameEn: "Abasa", ayahCount: 42, juz: 30 },
  { number: 81, nameAr: "التكوير", nameEn: "At-Takwir", ayahCount: 29, juz: 30 },
  { number: 82, nameAr: "الانفطار", nameEn: "Al-Infitar", ayahCount: 19, juz: 30 },
  { number: 83, nameAr: "المطففين", nameEn: "Al-Mutaffifin", ayahCount: 36, juz: 30 },
  { number: 84, nameAr: "الانشقاق", nameEn: "Al-Inshiqaq", ayahCount: 25, juz: 30 },
  { number: 85, nameAr: "البروج", nameEn: "Al-Buruj", ayahCount: 22, juz: 30 },
  { number: 86, nameAr: "الطارق", nameEn: "At-Tariq", ayahCount: 17, juz: 30 },
  { number: 87, nameAr: "الأعلى", nameEn: "Al-Ala", ayahCount: 19, juz: 30 },
  { number: 88, nameAr: "الغاشية", nameEn: "Al-Ghashiyah", ayahCount: 26, juz: 30 },
  { number: 89, nameAr: "الفجر", nameEn: "Al-Fajr", ayahCount: 30, juz: 30 },
  { number: 90, nameAr: "البلد", nameEn: "Al-Balad", ayahCount: 20, juz: 30 },
  { number: 91, nameAr: "الشمس", nameEn: "Ash-Shams", ayahCount: 15, juz: 30 },
  { number: 92, nameAr: "الليل", nameEn: "Al-Layl", ayahCount: 21, juz: 30 },
  { number: 93, nameAr: "الضحى", nameEn: "Ad-Duha", ayahCount: 11, juz: 30 },
  { number: 94, nameAr: "الشرح", nameEn: "Ash-Sharh", ayahCount: 8, juz: 30 },
  { number: 95, nameAr: "التين", nameEn: "At-Tin", ayahCount: 8, juz: 30 },
  { number: 96, nameAr: "العلق", nameEn: "Al-Alaq", ayahCount: 19, juz: 30 },
  { number: 97, nameAr: "القدر", nameEn: "Al-Qadr", ayahCount: 5, juz: 30 },
  { number: 98, nameAr: "البينة", nameEn: "Al-Bayyinah", ayahCount: 8, juz: 30 },
  { number: 99, nameAr: "الزلزلة", nameEn: "Az-Zalzalah", ayahCount: 8, juz: 30 },
  { number: 100, nameAr: "العاديات", nameEn: "Al-Adiyat", ayahCount: 11, juz: 30 },
  { number: 101, nameAr: "القارعة", nameEn: "Al-Qariah", ayahCount: 11, juz: 30 },
  { number: 102, nameAr: "التكاثر", nameEn: "At-Takathur", ayahCount: 8, juz: 30 },
  { number: 103, nameAr: "العصر", nameEn: "Al-Asr", ayahCount: 3, juz: 30 },
  { number: 104, nameAr: "الهمزة", nameEn: "Al-Humazah", ayahCount: 9, juz: 30 },
  { number: 105, nameAr: "الفيل", nameEn: "Al-Fil", ayahCount: 5, juz: 30 },
  { number: 106, nameAr: "قريش", nameEn: "Quraysh", ayahCount: 4, juz: 30 },
  { number: 107, nameAr: "الماعون", nameEn: "Al-Maun", ayahCount: 7, juz: 30 },
  { number: 108, nameAr: "الكوثر", nameEn: "Al-Kawthar", ayahCount: 3, juz: 30 },
  { number: 109, nameAr: "الكافرون", nameEn: "Al-Kafirun", ayahCount: 6, juz: 30 },
  { number: 110, nameAr: "النصر", nameEn: "An-Nasr", ayahCount: 3, juz: 30 },
  { number: 111, nameAr: "المسد", nameEn: "Al-Masad", ayahCount: 5, juz: 30 },
  { number: 112, nameAr: "الإخلاص", nameEn: "Al-Ikhlas", ayahCount: 4, juz: 30 },
  { number: 113, nameAr: "الفلق", nameEn: "Al-Falaq", ayahCount: 5, juz: 30 },
  { number: 114, nameAr: "الناس", nameEn: "An-Nas", ayahCount: 6, juz: 30 }
];

export const SURAH_STATUS_LABELS: Record<string, string> = {
  NOT_STARTED: "لم يبدأ",
  IN_PROGRESS: "قيد الحفظ",
  MEMORIZED: "محفوظ",
  NEEDS_REVISION: "يحتاج مراجعة"
};

export const SURAH_STATUS_CYCLE = [
  "NOT_STARTED",
  "IN_PROGRESS",
  "MEMORIZED",
  "NEEDS_REVISION"
] as const;
